name: Backend CI Test

on:
  push:
    branches: [ main,release, develop ]
  pull_request:
    branches: [ main,release, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run Tests with Maven
        run: |
          mvn test
          if [ $? -ne 0 ]; then
            echo "Tests failed"
            exit 1
          fi
